.PHONY: build dist redist install install-from-source clean uninstall

build:
	CYTHONIZE=1 ./setup.py build

dist:
	CYTHONIZE=1 ./setup.py sdist bdist_wheel

redist: clean dist

install:
	CYTHONIZE=1 pip install .

install-from-source: dist
	pip install dist/CLinAlg-0.0.tar.gz

clean:
	$(RM) -r build dist src/*.egg-info
	$(RM) -r src/CLinAlg/{AlgTool.c, AlgMatrix.c, AlgVector.c, AlgQuaternion.c, AlgLine.c, AlgTransformation.c, AlgSegment.c, AlgPlane.c, AlgWire.c, AlgSurface.c}
	$(RM) -r .pytest_cache
	find . -name __pycache__ -exec rm -r {} +
	#git clean -fdX

uninstall:
	pip uninstall CLinAlg